travis:
  secure:
    BINSTAR_TOKEN: zYsyTku8FX0oQ6Ry1dYiUrERk5P65pkVBXLwEJW5ItQasvcFds4qpc6SqXd0n9PEAYT6LDrtJ+hVtUqrSaUtpCYvJ4izumpHb8vV4hy9oAdDIY8v7JeuMU/RVi4MfJH6uifLEJGxG4xIw4dRHZuwExwVfq3jtk3A63TVrerskLBQMR6RMCyuWcor2uJ7tvKRVQWcgY78EJuzEUPit7vVI8m20DXIukAF4y6Bkr8H+xjWHWYG15WOtc+ovqReA8HqX1IBf73NTuXbKchdOHHZLBQt4rkF9b70gxrHrJpAPw8if9S3ezicGvbfQHidN4Zt6jj4REAobofvGwEEpuoQV+pmw/XGx2r73lWtj6ArjJZn/wYn6bEDIVLBU1owoHu3ERZgMuIBOqTP2lI5qWrOvcJtQ36NqBVkJAuDf3gmDmBySM3QZn7QSXxRxPWIvS7VTpZv1mu8sukmbQECyM8GG3LY6ZkKPznj4AbP+e3ETn6E0wssCToPXWV7ivTmGtoTrQca/vkV2qotvL8j5MyfV+AyhQYqIwUN8i/W3PjyInS7rI3m7gCQjLAYqjRzXVfybyl8WJOPIDsMlfTRBHOW2oNSfhJSyBGGtGE5rkyF0I6XP+8TYWk0xx06YACG/GAPfVDpAbYoMkZ/a/JZLIkd3CJWy4ZOJ2wQue6Qg8wir2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
